Repository UBC-MDS/DSCI-532_2025_24_police_killings, pull requests merged in 2025-02, with the labels that each got.

#9 add motivation and purpose
  reports/m1_proposal.md
Labels: documentation

#12 Moving on to the new dataset
  README.md
  data/proc/clean_data.csv
  data/raw/police_killings.csv
  data/raw/the-counted-2015.csv
  data/raw/the-counted-2016.csv
  environment.yaml
  notebooks/data_cleaning.ipynb
  reports/m1_proposal.md
Labels: enhancement

#26 Improve readme
  README.md
Labels: documentation

#28 App Implementation
  data/proc/clean_data.csv
  notebooks/data_cleaning.ipynb
  src/app.py
Labels: documentation, enhancement

#29 add server for deployment
  requirements.txt
  src/app.py
Labels: enhancement

#40 Minor fixes in README.md
  README.md
Labels: enhancement
